version: "3.9"

services:
  mongo:
    image: mongo
    restart: unless-stopped
    ports:
      - ${MONGO_PORT}:27017
    env_file:
      - .env
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASSWORD}
    volumes:
      - mongo_db:/data/db

  api:
    build:
      dockerfile: Dockerfile
      context: .
    depends_on:
      - mongo
    env_file:
      - .env
    expose:
      - ${PORT}
    ports:
      - 4000:4000
    volumes:
      - .:/usr/src/shortit_app

volumes:
  mongo_db:
