version: "3.9"

services:
  mongo:
    image: mongo
    restart: unless-stopped
    ports:
      - ${MONGO_PORT}:27017
    command: mongod --quiet --logpath /dev/null
    volumes:
      - ./data:/data/db
    logging:
      driver: "none"

  api:
    build:
      dockerfile: Dockerfile
      context: .
    depends_on:
      - mongo
    env_file:
      - .env
    ports:
      - "3000:3000"
    volumes:
      - ./src:/app/src
      - ./nodemon.json:/app/nodemon.json
      - /app/node_modules

volumes:
  mongo_db:
